modLoader = "kotlinforforge"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/TechTastic/hexsky/issues"
displayURL = "https://techtastic.github.io/hexsky/v/latest/master/en_us/"
license = "MIT"

[[mods]]
modId = "hexxyskies"
version = "${version}"
displayName = "Hexxy Skies"
authors = ["TechTastic", "walksanator"]
description = '''
Hexcasting x Valkyrien Skies Interop
'''
logoFile = "icon.png"

[[dependencies.hexxyskies]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexxyskies]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexxyskies]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hexxyskies]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hexxyskies]]
modId = "hexcasting"
mandatory = true
versionRange = "[${hexcasting_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hexxyskies]]
modId = "moreiotas"
mandatory = false
versionRange = "[${moreiotas_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hexxyskies]]
modId = "complexhex"
mandatory = false
versionRange = "[${complexhex_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hexxyskies]]
modId = "hexal"
mandatory = false
versionRange = "[${hexal_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hexxyskies]]
modId = "hexodus"
mandatory = false
versionRange = "[${hexodus_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hexxyskies]]
modId = "hexical"
mandatory = false
versionRange = "[${hexical_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hexxyskies]]
modId = "lapisworks"
mandatory = false
versionRange = "[${lapisworks_version},)"
ordering = "AFTER"
side = "BOTH"