modid = "hexxyskies"
book = "hexcasting:thehexbook"
default_lang = "en_us"
default_branch = "master"

resource_dirs = [  # top takes priority
    # hexdoc-only resources
    "resources",
    # resource dirs for Hexxy Skies
    "{$_common.src}/main/resources",
    { path="{$_common.src}/generated/resources", required=false },
    "{$_fabric.src}/main/resources",
    { path="{$_fabric.src}/generated/resources", required=false },
    "{$_forge.src}/main/resources",
    { path="{$_forge.src}/generated/resources", required=false },
    # other hexdoc plugins
    { modid="hexcasting" },
    { modid="hexodus" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hexxyskies/_export/generated"

[template]
icon = "icon.png"
include = [
    "hexxyskies",
    "hexodus",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Hexxy Skies"
author = "TechTastic"
show_landing_text = true

[extra.hexcasting]
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='ACTIONS.(?P<is_per_world>register|makePerWorld)\("(?P<name>[^"]+)"\) \{ ActionRegistryEntry\(\s+HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)' }
_per_world_value = "makePerWorld"

[[extra.hexcasting.pattern_stubs]]
path = "{$_common.kotlin}/registry/HexxySkiesPatterns.kt"
regex = "{^_pattern_regex}"
per_world_value = "{^_per_world_value}"

# platforms

[_common]
src = "../common/src"
kotlin = "{src}/main/kotlin/io/github/techtastic/hexxyskies"

[_fabric]
src = "../fabric/src"

[_forge]
src = "../forge/src"
